#!/usr/bin/env bash
#
# Bootstraps the machine by sourcing all scripts in bootstrap.d/

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

has() {
    command -v "$1" &>/dev/null
}

for file in "${BASH_SOURCE[0]}.d"/*.sh; do
    filename=$(basename "${file%.sh}")
    [[ $filename =~ ${BOOTSTRAP_FILTER:-.*} ]] || continue
    echo "Configuring $filename"
    source "$file"
done
