#!/bin/bash
#
# Bootstraps the machine by sourcing all scripts in ./bootstrap.d/

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

bold='\e[1;39m'
green='\e[32m'
white='\e[37m'
yellow='\e[33m'
reset='\e[0m'

has() { command -v "$1" &>/dev/null; }
debug() { printf "${green}[bootstrap]${reset} %s...\n" "$@"; }
debugw() { printf "${yellow}[bootstrap]${reset} %s!\n" "$@"; }
log() { printf "${bold}${green}==>${white} %s${reset}\n" "$@"; }
logw() { printf "${bold}${yellow}==>${white} %s${reset}\n" "$@"; }

confirm() {
    if [ -n "${NONINTERACTIVE:-}" ] || [ ! -t 0 ]; then
        return
    fi
    printf "Configure ${bold}${white}%s${reset}? (y/n)" "$1"
    read -rn1
    printf "\e[2K\r" # clear line
    [[ $REPLY =~ ^[Yy]$ ]]
}

log "Running bootstrap"

for file in "${BASH_SOURCE[0]}.d"/*.sh; do
    [[ $file =~ "##" ]] && continue
    filename=$(basename "${file%.sh}")

    # Allow skipping certain scripts
    if ! confirm "$filename"; then
        logw "Skipping $filename"
        continue
    fi

    log "Configuring $filename"
    # shellcheck source=/dev/null
    source "$file"
    echo
done

log "Bootstrap done!"
