apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
  - caFile: ""
    certFile: ""
    insecure_skip_tls_verify: false
    keyFile: ""
    name: stable
    password: ""
    url: https://kubernetes-charts.storage.googleapis.com/
    username: ""
