#!/bin/bash

yadm sparse-checkout set --no-cone '/*' '!/bootstrap'
if [ "$(yadm config local.class)" = "Home" ]; then
    yadm gitconfig status.showUntrackedFiles normal
fi

# Repeat command for private repo
if [ "${YADM_HOOK_REPO:?}" = ~/.local/share/yadm/repo.git ]; then
    yadm --yadm-repo ~/.local/share/yadm/repo-private.git "${YADM_HOOK_COMMAND:?}"
fi
