#!/bin/bash

# Yadm has extra latency due to auto-alt feature, so use git directly
export GIT_DIR="${YADM_HOOK_REPO:?}"

git sparse-checkout set --no-cone '/*' '!/bootstrap'
git config submodule.work.active false

case "$(git config local.class)" in
Home) git config status.showUntrackedFiles normal ;;
Work) git submodule update -q --init --remote ;;
esac

# Repeat command for private repo
# if [ "${YADM_HOOK_REPO:?}" = ~/.local/share/yadm/repo.git ]; then
#     yadm --yadm-repo ~/.local/share/yadm/repo-private.git "${YADM_HOOK_COMMAND:?}"
# fi
