add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[package]
disabled = true

[custom.sudo]
command = "echo '(sudo)'"
description = "Sudo credentials are cached"
when = "sudo -n true"
style = "bold yellow"
