theme = "onedark"

[editor]
color-modes = true
cursor-shape = { insert = "bar" }
file-picker = { hidden = false }

[keys.normal]
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
space.E = [
  ':sh rm -f /tmp/hx-yazi',
  ':insert-output yazi  --chooser-file=/tmp/hx-yazi',
  ':insert-output echo "\x1b[?1049h" > /dev/tty',
  ':open %sh{cat /tmp/hx-yazi}',
  ':redraw',
]
space.i = ":toggle lsp.display-inlay-hints"
"C-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
